### ISSUE TITLE
Non-published Draft Event

### ISSUE THREAD

**Issue by alterisian** [rughh/on_ruby#634]
So That: We can have draft version of events,
As A: Ruby Event Organiser
I Want To: Introduce a 'live' boolean flag
And: Allow secret url sharing. 
===
Motivation: If there's a group of 4 or 5 of you that are creating an event, you want to be able to share the draft details of the event, and iterate on them, until correct. Would be great to do this with the actual events system. 

Thoughts? 

I guess in reality the live flag, would really just mean it's not publically listed, and the normally generated url is still the shared url.

**Comment by phoet** [comment]
yes, that could be a helpful feature. i don't think that there needs to be a "secret url" as there isnt anything secret about organizing events, most of it is based on schedule and you might already know when the next one will be and so on...

what we actually do, when we organize an event is: we do this on github. because of this, you can link an issue-id to an event, so that people can see and contribute to the organization process.

our belief is, that everything should be as open and transparent as possible.
